Recipe.create!(title: 'Recipe 1', description: 'Recipe  1 description', ingredients: '{ [ingredient1, ingredient2, ingredient3] }')
Recipe.create!(title: 'Recipe 2', description: 'Recipe  2 description', ingredients: '{ [ingredient1, ingredient2, ingredient3] }')
Recipe.create!(title: 'Recipe 3', description: 'Recipe  3 description', ingredients: '{ [ingredient1, ingredient2, ingredient3] }')
Recipe.create!(title: 'Recipe 4', description: 'Recipe  4 description', ingredients: '{ [ingredient1, ingredient2, ingredient3] }')
Recipe.create!(title: 'Recipe 5', description: 'Recipe  5 description', ingredients: '{ [ingredient1, ingredient2, ingredient3] }')
